### PR TITLE
#37 Making KAR artifact creation

### PR DESCRIPTION
**Pull request by robertcsakany**
I've made the KAR creatin modification and I've deployed the created KAR file successfully.

### CODE REVIEW

**Comment by tobilarscheid** [comment]
Hi Robert,

super awesome - thank you very much!

To make this change really perfect we would need to adapt a few more things to show the KAR deployment:

- [ ] README
- [ ] script in the README downloading the KAR in the future
- [ ] Dockerfile of the example Dockercontainer

Let me know if I can assist you on any of these!

When we are done, I would release this as 3.0.0

Best,

Tobi

**Comment by robertcsakany** [comment]
Yes sure. In the next week I will check them.

**Comment by tobilarscheid** [comment]
Nice! As I said, I am here if you need help on any of these.

**Comment by robertcsakany** [comment]
Hi @tobilarscheid! Please check my pull request.

**Comment by tobilarscheid** [comment]
Hi @robertcsakany thanks for your great work! Just merged the PR!

**Pull request merged**
